# steps:
#   # Step 1: Build the Docker image
#   - name: 'gcr.io/cloud-builders/docker'
#     dir: 'backend'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend', '.']

#   # Step 2: Push the image to Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend']

#   # Step 3: Deploy to Cloud Run
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args:
#       - 'run'
#       - 'deploy'
#       - 'smartdrive-backend'
#       - '--image=us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend'
#       - '--region=us-central1'
#       - '--platform=managed'
#       - '--allow-unauthenticated'
#       - '--port=4000'
#       - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest,WEAVIATE_CLUSTER_URL=weaviate-cluster-url:latest,WEAVIATE_API_KEY=weaviate-api-key:latest'

# images:
#   - us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend

# options:
#   logging: CLOUD_LOGGING_ONLY
# This file defines the CI/CD pipeline for the smartdrive-backend Node.js service.

steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: 'Deploy'
    args:
      - 'run'
      - 'deploy'
      - 'smartdrive-backend'
      - '--image=us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest,WEAVIATE_URL=weaviate-url:latest,WEAVIATE_API_KEY=weaviate-api-key:latest'

images:
  - 'us-central1-docker.pkg.dev/smartdrive-461502/smartdrive-repo/smartdrive-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY